// Original lab content. The textbook links align concepts; simulated values are not textbook data.
export const stages = ['Interphase','Prophase','Metaphase','Anaphase','Telophase'];
export const stageClues = [
  'Intact nucleus with diffuse chromatin; no separate condensed chromosomes.',
  'Condensed chromosomes are visible but are not aligned at the middle. This lab groups prometaphase with prophase.',
  'Condensed chromosomes line up across the middle of the cell.',
  'Separated daughter chromosomes move toward opposite ends of the cell.',
  'Two new nuclei form; a developing cell plate may divide the plant cell.',
];
export const investigations = {
 'light-photosynthesis': {
  id:'light-photosynthesis',title:'Light and Photosynthesis',chapter:8,kind:'leaf',duration:'45–60 minutes',
  question:'How does light level affect the time it takes leaf disks to float?',
  overview:'First replace trapped air in leaf disks with solution so they sink. Then use the lamp to explore how light changes oxygen accumulation and flotation. For a controlled comparison, keep each trial at its assigned light level for 20 minutes; you can also change the lamp during a trial and examine the exploratory results.',
  conditions:[{id:'dark',label:'Dark control',detail:'0% relative light'},{id:'low',label:'Low light',detail:'25% relative light'},{id:'bright',label:'Bright light',detail:'100% relative light'}],
  interval:2,end:20,yLabel:'Floating disks (of 10)',max:10,
  constants:'10 same-sized disks, same leaf type, 0.2% sodium bicarbonate solution with a trace of detergent, solution depth, and temperature. Only light level changes.',
  materials:['Fresh spinach leaves; hole punch; three clear cups; needle-free syringe','0.2% sodium bicarbonate solution (0.2 g per 100 mL water), trace of dish detergent','LED light, foil or opaque cover, timer, thermometer; 10 disks per trial'],
  procedure:[
   'Make equal-sized leaf disks, avoiding major veins. Prepare matched cups of solution and label dark, low light, and bright light.',
   'In a needle-free syringe, immerse disks in solution, expel air, cover the tip, and gently draw back the plunger. Release and repeat until disks sink. Use the same preparation for every treatment.',
   'Put 10 sunken disks in each cup. Use a cover for darkness and a shade screen for lower light; keep depth, leaf source, and temperature matched. The virtual percentages are relative settings, not calibrated classroom illuminance.',
   'Count floating disks at 0, 2, 4, ... 20 minutes. Briefly observe the dark treatment with minimal illumination. Record counts even if they decrease or fail to reach five.',
   'Repeat with new disks for trials 2 and 3. Independent cups, rather than individual disks in a shared cup, are the experimental replicates. Pool independent trials from class groups for a single-period lab; sequential repeats require additional time.',
  ],
  safety:'Use a needle-free syringe and a cool LED light. Keep electrical equipment dry. Do not taste solutions. Teacher supervision is needed for hole punches and glassware.',
  model:'The interactive assay tracks an illustrative gas balance: light-driven production, continuing respiration, and gas loss. Disks can rise and later sink as lamp settings change. Rates, three preparation cycles, and disk variation are teaching assumptions, not calibrated predictions for a real leaf or lamp. Temperature and bicarbonate remain fixed. Modified-light or incompletely infiltrated trials are exploratory and are excluded from fixed-light means; their readings and lamp histories remain in CSV and text exports.',
  interpretation:'ET50 is the interpolated time when 5 of 10 disks float. Lower ET50 suggests faster net oxygen accumulation under matched conditions. If five disks never float, report “not reached within 20 minutes”; do not treat that as a zero rate.',
  questions:[
   'Which light condition had the shortest ET50? Support your claim with values from at least two treatments and discuss variation between trials.',
   'Why are the dark control and matched leaf preparation necessary?',
   'Explain how oxygen accumulation makes disks float and why this is an indirect measure of net activity, not a direct measurement of sugar production.',
   'Identify one limitation or source of uncertainty and propose an improved investigation.',
  ],
  teacherNotes:[
   'Virtual expectation: bright light generally reaches ET50 sooner than low light; darkness normally does not reach it during this model run. Exact times vary. Do not grade classroom results against the simulation.',
   'Students should connect light-driven oxygen production and buoyancy, and recognize that respiration and leaf preparation influence net flotation.',
   'If disks float at time zero, recheck infiltration. If none rise, check leaf condition, light, temperature, bicarbonate preparation, and excess detergent. Keep unexpected real observations; do not replace them with expected values.',
  ],
  sources:[['University of Arizona, floating leaf disk assay','https://mcb.arizona.edu/outreach/resources/science-at-home/photosynthesis'],['OpenStax Biology 2e, 8.2','https://openstax.org/books/biology-2e/pages/8-2-the-light-dependent-reactions-of-photosynthesis'],['College Board, Biology Investigative Labs, Investigation 5','https://secure-media.collegeboard.org/digitalServices/pdf/ap/bio-manual/CB_Bio_Full_Manual_2012.pdf']],
 },
 'yeast-fermentation': {
  id:'yeast-fermentation',title:'Yeast Fermentation and Fuel Sources',chapter:7,kind:'yeast',duration:'45–60 minutes',
  question:'How does the available sugar affect gas accumulation in a yeast culture?',
  overview:'Compare baker’s yeast with no added sugar, glucose, and sucrose. Record cumulative gas volume and compare average accumulation rates over the same time interval.',
  conditions:[{id:'none',label:'No added sugar',detail:'Water control'},{id:'glucose',label:'Glucose',detail:'2 g / 50 mL final mixture'},{id:'sucrose',label:'Sucrose',detail:'2 g / 50 mL final mixture'}],
  interval:5,end:30,yLabel:'Collected gas (mL)',max:100,
  constants:'0.5 g baker’s yeast, 50 mL final mixture, 30 °C water bath, identical gas collection apparatus, 30-minute observation. Sugar treatments have equal mass concentration, not equal molarity.',
  materials:['Baker’s yeast, glucose, sucrose, water, balance, thermometer and timer','Three matched flasks and tubing connected to freely moving 100 mL gas syringes','Teacher-prepared 30 °C water bath; matched mixtures at 50 mL final volume'],
  procedure:[
   'Label matched setups no added sugar, glucose, and sucrose. Prepare each sugar mixture with 2 g sugar; the water control receives no added sugar.',
   'Add 0.5 g yeast to each and adjust to 50 mL final volume. Use the same yeast batch and equilibration time. Maintain 30 °C with a water bath.',
   'Connect each flask to a freely moving gas syringe. Check for leaks and unobstructed motion. Record the initial gas reading and subtract it from subsequent readings.',
   'Record cumulative gas at 0, 5, 10, ... 30 minutes. Do not compare foam height or balloon circumference with the app’s milliliter values.',
   'Repeat with fresh mixtures for trials 2 and 3. Pool independent trials from class groups for a single-period lab; sequential repeats require additional time. Compare volume change divided by elapsed time, retain outliers, and explain suspected problems.',
  ],
  safety:'Use baker’s yeast only. Do not taste cultures. Never seal gas production in a rigid closed container or block the syringe plunger. Stop before apparatus capacity is reached. Teacher checks glassware and warm-water handling.',
  model:'Volumes are illustrative, generated curves with a lag and trial variation. Glucose and sucrose responses overlap; their ranking is not universal. The water control can show small background gas. The model does not establish anaerobic conditions or identify collected gas chemically.',
  interpretation:'Average gas accumulation rate = (final volume − initial volume) / elapsed minutes. Gas from yeast is consistent with CO₂ production, but volume alone does not prove fermentation rather than aerobic metabolism or directly measure ATP yield.',
  questions:[
   'Compare the mean gas accumulation rates for the three treatments. Use numerical evidence and discuss overlap between trials.',
   'Why include yeast with no added sugar? What additional control would help separate yeast activity from physical gas expansion?',
   'Explain how fermentation supports continued glycolysis. Why can gas volume alone not establish the amount of ATP made or prove oxygen was absent?',
   'Identify one limitation of equal-mass sugar comparisons or gas collection, and propose a better experiment.',
  ],
  teacherNotes:[
   'Virtual expectation: both sugar treatments accumulate more gas than the no-added-sugar control. Glucose and sucrose may exchange rank across trials. Encourage evidence-based comparison rather than a fixed “winning sugar.”',
   'Fermentation regenerates NAD+ so glycolysis can continue. Fermentation and anaerobic respiration are different pathways; yeast gas volume does not uniquely establish which metabolic processes occurred.',
   'No-added-sugar is not necessarily zero because yeast has internal reserves and apparatus has background effects. A no-yeast control and leak/temperature checks strengthen the inference.',
  ],
  sources:[['OpenStax Biology 2e, 7.5','https://openstax.org/books/biology-2e/pages/7-5-metabolism-without-oxygen']],
 },
 'mitosis': {
  id:'mitosis',title:'Measuring Mitosis',chapter:10,kind:'mitosis',duration:'40–55 minutes',
  question:'What can a snapshot of dividing cells tell us about the cell cycle?',
  overview:'Classify cells in two schematic root-tip fields or count prepared classroom slides. Use stage frequencies to estimate time in each stage under an explicitly assumed cycle duration.',
  conditions:[{id:'field-a',label:'Field A',detail:'20 schematic cells'},{id:'field-b',label:'Field B',detail:'20 schematic cells'}],
  constants:'Use the same scoring definitions and count every cell in each selected field. Group prometaphase with prophase; count telophase/cytokinesis as one event until daughter cells are separated.',
  materials:['Prepared onion root-tip slides, microscope, stage tally sheet','Alternatively: the app’s two schematic fields, with no equipment needed','Calculator; teacher-selected cycle duration (24 hours is an assumption, not a measured value)'],
  procedure:[
   'Review the reference diagrams and stage definitions. Interphase includes G1, S, and G2; these are not distinguished in this activity.',
   'Locate a root-tip meristem on a prepared slide at low magnification, then increase magnification to resolve chromosomes. Use fine focus as appropriate.',
   'Choose a systematic field and count every interpretable cell without selecting only dividing cells. Record excluded or ambiguous cells in notes.',
   'Classify cells as interphase, prophase (including prometaphase), metaphase, anaphase, or telophase. Record a second non-overlapping field.',
   'Calculate each stage count / total count × 100. Multiply that fraction by the assumed cycle duration. Explain the assumptions needed to turn a snapshot into a time estimate.',
  ],
  safety:'Use prepared slides only. Carry microscopes with two hands and handle slide edges carefully. The classroom route does not require stains, acids, or cutting root tips.',
  model:'The virtual fields are original teaching diagrams, not microscope photographs or empirical samples. Each contains 20 cells. They practice recognition and frequency calculations; the curated distribution is not a validated biological estimate.',
  interpretation:'Estimated stage time = stage count / total count × assumed cycle duration. This assumes representative sampling of an asynchronous, steadily cycling population with comparable cycle lengths. Non-cycling cells, sampling bias, and differential cell loss can invalidate the estimate.',
  questions:[
   'Which stage is most common? Give its count, percentage, and estimated duration, and distinguish observation from inference.',
   'Describe the chromosome evidence you used to distinguish metaphase from anaphase. Why does interphase count even though it is not mitosis?',
   'What assumptions are required to infer time from stage frequency? Explain why 24 hours is not a measured onion cell-cycle duration here.',
   'Compare the two fields and identify one sampling limitation. Explain how you would improve the count.',
  ],
  teacherNotes:[
   'The schematic fields together contain 27 interphase, 6 prophase, 3 metaphase, 2 anaphase, and 2 telophase cells (40 total). Order is shuffled per attempt. Review feedback appears only after all cells in a virtual field are classified.',
   'At an assumed 24-hour cycle, the modeled durations are 16.2, 3.6, 1.8, 1.2, and 1.2 hours respectively. These are worked examples for the schematic sample, not reference durations for real roots.',
   'Score the quality of morphological evidence and limitations. Classroom counts should not be corrected to match the schematic distribution. In this simplified key, prometaphase is pooled with prophase.',
  ],
  sources:[['OpenStax Biology 2e, 10.2','https://openstax.org/books/biology-2e/pages/10-2-the-cell-cycle']],
 },
};
export const buildOrder = ['light-photosynthesis','yeast-fermentation','mitosis'];
