import {test,expect} from '@playwright/test';

test('equation practice checks matter and symbols, restores, and separates models',async({page})=>{
  await page.goto('/investigation.html?lab=light-photosynthesis');
  await page.getByText('Optional activity: build the photosynthesis and respiration equations',{exact:true}).click();
  const activity=page.locator('equation-builder');
  await activity.getByRole('button',{name:'Check arrangement'}).click();
  await expect(activity.getByRole('status')).toContainText('0 / 9');
  const photo={oxygen:'products',glucose:'products',water:'reactants',co2:'reactants',heat:'unused',chlorophyll:'arrow',atp:'unused',light:'arrow',mitochondrion:'unused'};
  for(const [card,zone] of Object.entries(photo))await activity.locator(`[data-card="${card}"]`).selectOption(zone);
  await activity.getByRole('button',{name:'Check arrangement'}).click();
  await expect(activity.getByRole('status')).toContainText('9 / 9');
  await expect(activity.getByRole('status')).toContainText('reactants 6, 12, 18; products 6, 12, 18');
  await page.reload();
  await page.getByText('Optional activity: build the photosynthesis and respiration equations',{exact:true}).click();
  await expect(activity.getByRole('status')).toContainText('9 / 9');
  await activity.getByLabel('Choose a model').selectOption('resp');
  await expect(activity.locator('[data-card="oxygen"]')).toHaveValue('bank');
  const resp={oxygen:'reactants',glucose:'reactants',water:'products',co2:'products',heat:'energy',chlorophyll:'unused',atp:'energy',light:'unused',mitochondrion:'arrow'};
  for(const [card,zone] of Object.entries(resp))await activity.locator(`[data-card="${card}"]`).selectOption(zone);
  await activity.getByRole('button',{name:'Check arrangement'}).click();
  await expect(activity.getByRole('status')).toContainText('9 / 9');
  await expect(activity.getByRole('status')).toContainText('reactants 6, 12, 18; products 6, 12, 18');
  await page.setViewportSize({width:390,height:844});
  await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/equation-mobile.png',fullPage:true});
  await activity.getByRole('button',{name:'Reset this model'}).click();
  await expect(activity.locator('[data-card="oxygen"]')).toHaveValue('bank');
  await activity.getByLabel('Choose a model').selectOption('photo');
  await expect(activity.getByRole('status')).toContainText('9 / 9');
  await page.goto('/investigation.html?lab=yeast-fermentation');
  await page.getByText('Optional activity: build the photosynthesis and respiration equations',{exact:true}).click();
  await expect(activity.getByLabel('Choose a model')).toHaveValue('resp');
  await expect(activity).toContainText('Fermentation does not use oxygen');
});
