import './preview.js';
import './library.css';
import {units,labs,labPath,searchCatalog} from './catalog.js';
const app=document.querySelector('#app');
const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=(path,label,cls='')=>`<a class="${cls}" href="#${path}">${escape(label)}</a>`;
const badge=lab=>`<span class="badge ${lab.status}">${lab.status==='available'?'Available · Virtual':'Planned'}</span>`;
function labCard(lab){return `<article class="card lab-card">${badge(lab)}<h3>${link(labPath(lab),lab.title)}</h3><p>${lab.summary}</p><p class="reference">Biology 2e · Chapter ${lab.chapter}: ${lab.chapterTitle}</p>${link(labPath(lab),lab.status==='available'?'Explore lab →':'View plan →','text-link')}</article>`;}
function unitCard(unit){return `<article class="card"><span class="eyebrow">UNIT ${unit.number} / BIOLOGY</span><h3>${link(`/science/biology/${unit.id}`,unit.title)}</h3><p>${unit.description}</p><div class="card-bottom"><span>${unit.end-unit.start+1} lab plans${unit.id==='the-cell'?' · 1 available':''}</span>${link(`/science/biology/${unit.id}`,'Explore unit →','text-link')}</div></article>`;}
function hero(kicker,title,description,extra=''){return `<section class="hero"><div><p class="eyebrow">${kicker}</p><h1 tabindex="-1">${title}</h1><p class="lead">${description}</p>${extra}</div><div class="science-art" aria-hidden="true"><div class="orbit o1"></div><div class="orbit o2"></div><div class="orbit o3"></div><div class="nucleus"></div><span class="art-caption">OBSERVE / QUESTION / DISCOVER</span></div></section>`;}
function render(){
 const url=new URL((location.hash.slice(1)||'/'),'https://library.local');
 const path=url.pathname.replace(/\/$/,'')||'/';
 const query=url.searchParams.get('q')||'';
 const parts=path.split('/').filter(Boolean);
 const unit=parts[0]==='science'&&parts[1]==='biology'?units.find(u=>u.id===parts[2]):null;
 const lab=unit?labs.find(l=>l.id===parts[3]&&l.unitId===unit.id):null;
 let body='',title='Science Labs',crumbs=[['/','Home']];
 if(path==='/'){
 body=hero('A SPACE FOR CURIOSITY','Big questions.<br>Real discoveries.','Explore labs and interactives that bring science to life. Start with a subject, follow your curiosity, and investigate.',link('/science','Explore science →','button'))+
 `<section><div class="section-heading"><div><p class="eyebrow">EXPLORE THE LIBRARY</p><h2>Find your next investigation</h2></div><span>Growing one discovery at a time</span></div><div class="grid"><article class="card subject-card"><span class="subject-icon" aria-hidden="true">◎</span><p class="eyebrow">SUBJECT AREA</p><h3>${link('/science','Science')}</h3><p>Explore living systems, test ideas, and make sense of the natural world.</p>${link('/science','Browse science →','text-link')}</article><article class="card feature"><p class="eyebrow">START INVESTIGATING</p><h3>How does water move across a membrane?</h3><p>Explore our first virtual lab with model cells in five different environments.</p>${link(labPath(labs[4]),'Explore osmosis and cell homeostasis →','text-link')}</article></div></section>`+
 `<section class="teaching-note"><p class="eyebrow">BUILT AROUND YOUR CLASSROOM</p><h2>A growing library for flexible teaching</h2><p>Start with the available virtual investigation. Classroom activities and teacher-selected combinations are planned as the library grows.</p></section>`;
 }else if(path==='/science'){
 title='Science';crumbs.push(['/science','Science']);
 body=hero('EXPLORE / SCIENCE','Follow the evidence.','Discover investigations organized by discipline. Biology is the first collection in our growing science library.')+`<section><h2>Choose a discipline</h2><div class="grid"><article class="card subject-card"><p class="eyebrow">LIFE SCIENCE</p><h3>${link('/science/biology','Biology')}</h3><p>From molecules to ecosystems: eight units of investigations into living things.</p><div class="card-bottom"><span>8 units · 47 lab plans</span>${link('/science/biology','Explore biology →','text-link')}</div></article></div></section>`;
 }else if(path==='/science/biology'){
 title='Biology';crumbs.push(['/science','Science'],[path,'Biology']);
 body=hero('SCIENCE / BIOLOGY','Investigate living things.','Explore cells, inheritance, organisms, and ecosystems. Choose a unit to find its labs and planned investigations.',`<div class="stats"><span><strong>8</strong> units</span><span><strong>47</strong> lab plans</span><span><strong>1</strong> available now</span></div>`)+`<section><div class="section-heading"><h2>Explore the units</h2><span>Aligned to OpenStax Biology 2e</span></div><div class="grid">${units.map(unitCard).join('')}</div></section>`;
 }else if(unit&&parts.length===3){
 title=unit.title;crumbs.push(['/science','Science'],['/science/biology','Biology'],[path,unit.title]);
 body=hero(`BIOLOGY / UNIT ${unit.number}`,unit.title,unit.description)+`<section><div class="section-heading"><h2>Labs in this unit</h2><span>Textbook references appear in each description</span></div><div class="grid">${labs.filter(l=>l.unitId===unit.id).map(labCard).join('')}</div></section>`;
 }else if(lab&&parts.length===4){
 title=lab.title;crumbs.push(['/science','Science'],['/science/biology','Biology'],[`/science/biology/${unit.id}`,unit.title],[path,lab.title]);
 body=`<section class="detail"><p class="eyebrow">BIOLOGY / ${escape(unit.title)}</p>${badge(lab)}<h1 tabindex="-1">${lab.title}</h1><p class="lead">${lab.summary}</p><p class="reference">Textbook connection: OpenStax Biology 2e, Chapter ${lab.chapter}: ${lab.chapterTitle}.</p><div class="detail-panel"><h2>${lab.status==='available'?'Ready to investigate':'An investigation in the making'}</h2><p>${lab.status==='available'?'Explore the virtual dialysis-tubing investigation. Your progress is saved in this browser on this device.':'This page describes a proposed lab. Activities, materials, and assessments have not been developed yet.'}</p>${lab.launchUrl?`<a class="button" href="${lab.launchUrl}">Launch virtual lab →</a>`:'<p>Planned direction: virtual and classroom activities with shared analysis questions.</p>'}</div>${link(`/science/biology/${unit.id}`,'← Back to the unit','text-link')}</section>`;
 }else if(path==='/search'){
 title='Search';crumbs.push([path,'Search']);const available=url.searchParams.get('available')==='1';const results=searchCatalog(query,{availableOnly:available});
 body=`<section class="search-page"><p class="eyebrow">EXPLORE THE LIBRARY</p><h1 tabindex="-1">Find an investigation</h1><form class="search-large" data-search><label for="query">Search by topic, lab title, unit, or chapter</label><div class="search-row"><input id="query" name="q" type="search" value="${escape(query)}" placeholder="Try osmosis, genetics, or chapter 8"><button>Search</button></div><label class="check"><input type="checkbox" name="available" value="1" ${available?'checked':''}> Available labs only</label></form><p role="status">${results.length} ${results.length===1?'investigation':'investigations'}${query?` matching “${escape(query)}”`:''}</p>${results.length?`<div class="grid">${results.map(labCard).join('')}</div>`:`<div class="empty"><h2>No matching investigations</h2><p>Try a broader topic such as cells, plants, or ecology, or remove the availability filter.</p>${link('/search','Browse all investigations','text-link')}</div>`}</section>`;
 }else{title='Page not found';body=`<section class="detail"><h1 tabindex="-1">That page isn’t in the library.</h1><p>Explore a subject or search for an investigation.</p>${link('/','Back to home','button')}</section>`;}
 document.title=`${title==='Science Labs'?title:title+' | Science Labs'}`;
 app.innerHTML=`<a class="skip-link" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="#/" aria-label="Science Labs home"><span class="brand-mark" aria-hidden="true">✳</span> Science<span class="brand-light">Labs</span></a><nav aria-label="Main navigation">${link('/science','Science',parts[0]==='science'?'active':'')}${link('/science/biology','Biology',parts[1]==='biology'?'active':'')}</nav><form class="header-search" data-search role="search"><label class="sr-only" for="header-query">Search the library</label><input id="header-query" name="q" type="search" placeholder="Search the library" value="${escape(query)}"><button aria-label="Submit library search">Search</button></form></header><main id="main"><nav class="breadcrumbs" aria-label="Breadcrumb">${crumbs.map(([p,label],i)=>i===crumbs.length-1?`<span aria-current="page">${escape(label)}</span>`:link(p,label)).join('<span aria-hidden="true">/</span>')}</nav>${body}</main><footer class="site-footer"><a class="brand" href="#/">Science Labs</a><p>Room to question. Space to discover.</p><span>Open access · No account needed</span></footer>`;
 app.querySelectorAll('[data-search]').forEach(form=>form.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(form);const params=new URLSearchParams();params.set('q',String(data.get('q')||'').trim());if(data.has('available'))params.set('available','1');location.hash='/search?'+params;}));
 app.querySelector('.skip-link').addEventListener('click',event=>{event.preventDefault();app.querySelector('h1').focus();});
}
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);app.querySelector('h1')?.focus({preventScroll:true});});
render();
if('serviceWorker' in navigator&&import.meta.env.PROD)navigator.serviceWorker.register(`${import.meta.env.BASE_URL}sw.js`,{updateViaCache:'none'}).catch(()=>{});
