import './style.css';
import {refreshLabCache} from './cache.js';
import {preparation,sugarDish} from './components/preparation.js';
import {labConfig as c} from './data/labConfig.js';
import {freshState,restore,all,correct,advance,difference} from './state.js';
import {beaker,tube,balance,graph} from './components/equipment.js';
let s;try{s=restore(localStorage.getItem('cell-lab'));}catch{s=freshState();}
let selected='A', prep=0, tared=false, message='', busy=false, animation='';
const titles=['Welcome to the lab','Prepare the beakers','Examine the model cells','Place the cells','Run the experiment','Final measurements','Your results'];
const save=()=>{try{localStorage.setItem('cell-lab',JSON.stringify({version:2,state:s}));}catch{message='Browser storage unavailable. Keep this tab open to preserve your work.';}};
const escape=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const button=(action,label,disabled=false)=>`<button data-action="${action}" ${disabled?'disabled':''}>${label}</button>`;
const cards=(mode)=>`<div class="equipment">${c.beakers.map(b=>`<button class="card ${selected===b.id?'selected':''}" data-select="${b.id}" aria-pressed="${selected===b.id}" ${mode==='place'?'data-drop="'+b.id+'"':''}>${mode==='tube'?tube(b.id):beaker(b,!!s.prepared[b.id],!!s.placed[b.id]&&s.step>=3)}<strong>${mode==='tube'?'Tube':'Beaker'} ${b.id}</strong><span>${mode==='tube'?s.initial[b.id]?'Measured':'Inspect & weigh':`${b.sugarPercent}% sugar`}</span><small>${mode==='prepare'?s.prepared[b.id]?'Prepared · Record this beaker on your lab sheet':'Not prepared':mode==='place'?s.placed[b.id]?'Tube placed':'Awaiting tube':''}</small></button>`).join('')}</div>`;
const notebook=()=>`<div class="table-wrap"><table><caption>Lab notebook · measurements in grams</caption><thead><tr><th>Tube</th><th>Initial mass (g)</th><th>Final mass (g)</th><th>Change (g)</th></tr></thead><tbody>${s.run.map(t=>`<tr><th>${t.id}</th><td>${s.initial[t.id]?t.initialMass.toFixed(2)+' g':'—'}</td><td>${s.final[t.id]?t.finalMass.toFixed(2)+' g':'—'}</td><td>${s.valid[t.id]?escape(s.answers[t.id])+' g':'—'}</td></tr>`).join('')}</tbody></table></div>`;
function ready(){return [true,all(s.prepared),all(s.initial),all(s.placed),s.elapsed,all(s.final)&&all(s.valid),false][s.step];}
function content(){const b=c.beakers.find(b=>b.id===selected),t=s.run.find(t=>t.id===selected);
switch(s.step){case 0:return `<div class="intro"><span class="eyebrow">BIOLOGY / MEMBRANES & TRANSPORT</span><h2>Small cells.<br>Different environments.</h2><p class="question">What happens to a cell when it is in different environments?</p><p>Use dialysis tubing as a model cell. Investigate how external sugar concentrations affect the movement of water across a selectively permeable membrane.</p><div class="facts"><span>5 environments</span><span>${c.experimentHours}-hour experiment</span><span>No account needed</span></div>${button('next','Begin Lab →')}</div>${cards('intro')}`;
case 1:return `<p>Prepare each solution: measure water, tare the empty dish, weigh sugar, then add it to the beaker.</p>${cards('prepare')}<section class="workspace"><div><h3>Solution ${b.id} · ${b.sugarPercent}% sugar</h3><p>${b.waterMl} mL water + ${b.sugarGrams} g sugar</p><p>Classroom approximation: sugar addition does not change the stated volume. Concentrations are % w/v.</p><p>The empty petri dish weighs ${c.dishMass} g. Taring subtracts the dish so the display measures sugar alone.</p>${preparation(b,prep,tared,animation,!!s.prepared[b.id])}</div><div><div class="scale-station">${sugarDish(prep>=2&&!s.prepared[b.id]&&b.sugarGrams>0,b.sugarGrams)}${balance(prep>=2&&!s.prepared[b.id]?b.sugarGrams+(tared?0:c.dishMass):tared?0:c.dishMass,prep>=2&&!s.prepared[b.id]?'Dish with sugar':'Empty petri weighing dish')}</div><div class="actions">${button('water',prep>=1?'Water measured ✓':'Turn on faucet · Measure & add water',prep>=1||s.prepared[b.id])}${button('tare',tared?'Balance zeroed ✓':'Tare / Zero',prep!==1||s.prepared[b.id])}${button('sugar','Weigh sugar · place on scale',!tared||prep!==1||s.prepared[b.id])}${button('mix',s.prepared[b.id]?'Solution prepared ✓':'Add sugar & mix',prep!==2||s.prepared[b.id])}</div></div></section>`;
case 2:return `<p>Dialysis tubing represents a cell with a selectively permeable membrane. Inspect and weigh all five tubes.</p>${cards('tube')}<section class="workspace"><div><h3>Tube ${t.id}</h3><p>Inside: ${t.sugarPercent}% sugar solution</p><p>Initial mass: ${s.initial[t.id]?t.initialMass.toFixed(2)+' g':'Place on the balance to measure'}</p></div><div>${balance(s.initial[t.id]?t.initialMass:0,'Laboratory balance')}${button('initial',s.initial[t.id]?'Mass recorded ✓':'Weigh & record initial mass',!!s.initial[t.id])}</div></section>`;
case 3:return `<p>Place each tube into its matching beaker. Select a beaker and tap Place, or drag the labeled tube to its beaker.</p><div class="tube-tray">${s.run.map(t=>`<button draggable="true" data-drag="${t.id}" data-select="${t.id}" ${s.placed[t.id]?'disabled':''}>${tube(t.id)}Tube ${t.id}</button>`).join('')}</div>${cards('place')}${button('place',`Place tube ${selected} in beaker ${selected}`,!!s.placed[selected])}`;
case 4:return `<p>All five model cells are in their environments. Advance the clock to complete the experiment.</p>${cards('experiment')}<div class="time ${busy?'running':''}" aria-live="polite"><span class="clock">◷</span><h3>${s.elapsed?c.experimentHours:0} hours elapsed</h3>${button('advance',s.elapsed?'Experiment complete ✓':busy?'Time advancing…':`Advance ${c.experimentHours} Hours`,s.elapsed||busy)}</div>`;
case 5:return `<p>Remove and weigh each tube. Calculate final mass − initial mass in grams, including the sign.</p>${cards('tube')}<section class="workspace"><div><h3>Tube ${t.id}</h3><p>Initial mass: ${t.initialMass.toFixed(2)} g</p>${s.final[t.id]?`<p>Final mass: ${t.finalMass.toFixed(2)} g</p><form id="calculation"><label for="answer">Change in mass (g)</label><input id="answer" name="answer" type="number" step="any" value="${escape(s.answers[t.id])}" required><button>Check calculation</button></form>${(s.attempts[t.id]||0)>=3?button('hint','Show Calculation'):''}`:''}</div><div>${balance(s.final[t.id]?t.finalMass:0,'Removed tube on balance')}${button('final',s.final[t.id]?'Final mass recorded ✓':'Remove, weigh & record',!!s.final[t.id])}</div></section>`;
case 6:return `<p>Compare your observations. Use the table and graph to complete your worksheet.</p><div class="table-wrap"><table><caption>Experiment results</caption><thead><tr>${['Tube','External sugar %','Internal sugar %','Initial (g)','Final (g)','Change (g)','Environment'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${s.run.map((t,i)=>{const b=c.beakers[i];return `<tr><th>${t.id}</th><td>${b.sugarPercent}</td><td>${t.sugarPercent}</td><td>${t.initialMass.toFixed(2)} g</td><td>${t.finalMass.toFixed(2)} g</td><td>${difference(t)} g</td><td>${b.sugarPercent<t.sugarPercent?'Hypotonic':b.sugarPercent===t.sugarPercent?'Isotonic':'Hypertonic'}</td></tr>`}).join('')}</tbody></table></div>${graph(s.run)}<div class="explanation"><h3>Connecting the observations</h3><p>Water crosses the membrane; sugar is retained. Lower external sugar concentration means net movement of water into the tube. Higher external concentration means net movement out. Equal concentrations give little or no net movement, although water still moves both ways.</p><p>The pure-water beaker provides a comparison with no external sugar. An isotonic tube has no net water movement because internal and external concentrations match.</p><p>Why did the masses of dialysis tubes A and D change very little over the 24-hour time period?</p><p>Which tube changed least? How do these results help answer the guided question?</p></div>`;}}
function render(focus=false){document.querySelector('#app').innerHTML=`<header><div class="brand">◉ <span>Cell Homeostasis<small>VIRTUAL LAB</small></span></div><button class="secondary" data-action="reset">Reset Lab</button></header><main><div class="step-label">STEP ${s.step+1} OF 7 <span>MODEL CELL INVESTIGATION</span></div><div class="progress" aria-label="Step ${s.step+1} of 7">${titles.map((_,i)=>`<span class="${i<=s.step?'done':''}"></span>`).join('')}</div><h1 tabindex="-1">${titles[s.step]}</h1><div class="notice">${c.dataStatus}</div>${content()}<p class="feedback" role="status">${escape(message)}</p>${s.step>1&&s.step<6?notebook():''}${s.step>0?`<nav>${button('back','← Back')}<span>${s.step===6?'Investigation complete':'Complete this step to continue'}</span>${s.step<6?button('next',s.step===3?'Begin Experiment →':'Continue →',!ready()):''}</nav>`:''}</main><footer>Answers stay on this device · No analytics · Designed for your lab worksheet</footer>`;if(busy)document.querySelectorAll('button').forEach(b=>b.disabled=true);if(focus)document.querySelector('h1').focus();}
async function animatePreparation(name){const duration={filling:8000,weighing:4000,mixing:8000,checking:1000}[name];busy=true;animation=name;render();document.querySelector('.workspace').style.setProperty('--prep-duration',`${duration}ms`);await new Promise(r=>setTimeout(r,matchMedia('(prefers-reduced-motion: reduce)').matches?0:duration));busy=false;animation='';}
document.addEventListener('click',async e=>{const el=e.target.closest('button');if(!el||el.disabled||busy)return;if(el.dataset.select){selected=el.dataset.select;prep=0;tared=false;message='';render();return;}const action=el.dataset.action;if(!action)return;message='';switch(action){case 'reset':if(!confirm('Reset all lab progress and measurements?'))return;s=freshState();try{localStorage.removeItem('cell-lab');}catch{}selected='A';prep=0;tared=false;save();busy=true;render(true);try{await refreshLabCache();message='Lab reset. Offline copies refreshed when online.';}catch{message='Lab reset. Cache refresh unavailable in this browser.';}busy=false;render(true);return;case 'next':if(ready())s.step++;break;case 'back':s.step=Math.max(0,s.step-1);break;case 'water':if(prep!==0||s.prepared[selected])return;await animatePreparation('filling');prep=1;message=`Faucet filled beaker ${selected} with ${c.beakers.find(b=>b.id===selected).waterMl} mL of water.`;break;case 'tare':tared=true;message='The empty dish now reads zero. Its mass will not be counted as sugar.';break;case 'sugar':if(!tared||prep!==1)return;await animatePreparation(c.beakers.find(b=>b.id===selected).sugarGrams>0?'weighing':'checking');prep=2;message='Sugar placed on the tared balance. Read the mass in grams.';break;case 'mix':if(prep!==2||s.prepared[selected])return;await animatePreparation(c.beakers.find(b=>b.id===selected).sugarGrams>0?'mixing':'checking');s.prepared[selected]=true;message='Sugar added and dissolved. Solution prepared.';break;case 'initial':s.initial[selected]=true;break;case 'place':s.placed[selected]=true;break;case 'advance':if(!all(s.placed))return;busy=true;render();await new Promise(r=>setTimeout(r,900));advance(s);busy=false;break;case 'final':s.final[selected]=true;break;case 'hint':{const t=s.run.find(t=>t.id===selected);message=`${t.finalMass.toFixed(2)} − ${t.initialMass.toFixed(2)} = ${difference(t)} g`;break;}}save();render(action==='next'||action==='back');});
document.addEventListener('submit',e=>{if(e.target.id!=='calculation')return;e.preventDefault();const v=new FormData(e.target).get('answer');s.answers[selected]=v;s.attempts[selected]=(s.attempts[selected]||0)+1;s.valid[selected]=correct(s.run,selected,v);message=s.valid[selected]?'Calculation recorded ✓':'Check your subtraction and try again.';save();render();});
document.addEventListener('input',e=>{if(e.target.id==='answer'){s.answers[selected]=e.target.value;s.valid[selected]=false;save();}});
document.addEventListener('dragstart',e=>{const el=e.target.closest('[data-drag]');if(el)e.dataTransfer.setData('text/plain',el.dataset.drag);});
document.addEventListener('dragover',e=>{if(e.target.closest('[data-drop]'))e.preventDefault();});
document.addEventListener('drop',e=>{const el=e.target.closest('[data-drop]');if(!el)return;e.preventDefault();const id=e.dataTransfer.getData('text/plain');if(id===el.dataset.drop){s.placed[id]=true;message=`Tube ${id} placed.`;}else message='Place the tube in its matching labeled beaker.';save();render();});
save();
render();
if('serviceWorker' in navigator&&import.meta.env.PROD){
  const alreadyControlled=!!navigator.serviceWorker.controller;
  let reloading=false;
  navigator.serviceWorker.addEventListener('controllerchange',()=>{
    if(alreadyControlled&&!reloading){reloading=true;save();location.reload();}
  });
  navigator.serviceWorker.register(`${import.meta.env.BASE_URL}sw.js`,{updateViaCache:'none'})
    .then(registration=>registration.update()).catch(()=>{});
}
